"""initial

Revision ID: f907662aa0d6
Revises:
Create Date: 2026-02-11 12:49:16.647265

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "f907662aa0d6"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
